// Code generated by MockGen. DO NOT EDIT.
// Source: adapters/adapter.go

// Package mockgen is a generated GoMock package.
package mockgen

import (
	context "context"
	sql "database/sql"
	http "net/http"

	gomock "github.com/golang/mock/gomock"
	adapters "github.com/prest/prest/v2/adapters"
)

// MockAdapter is a mock of Adapter interface.
type MockAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockAdapterMockRecorder
}

// MockAdapterMockRecorder is the mock recorder for MockAdapter.
type MockAdapterMockRecorder struct {
	mock *MockAdapter
}

// NewMockAdapter creates a new mock instance.
func NewMockAdapter(ctrl *gomock.Controller) *MockAdapter { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdapter) EXPECT() *MockAdapterMockRecorder {
	_ = "STUB: not implemented"

	// BatchInsertCopy mocks base method.
	return nil
}

func (m *MockAdapter) BatchInsertCopy(dbname, schema, table string, keys []string, params ...interface{}) adapters.Scanner {
	_ = "STUB: not implemented"
	return *new(adapters.Scanner)
}

// BatchInsertCopy indicates an expected call of BatchInsertCopy.
func (mr *MockAdapterMockRecorder) BatchInsertCopy(dbname, schema, table, keys interface{}, params ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// BatchInsertCopyCtx mocks base method.
func (m *MockAdapter) BatchInsertCopyCtx(ctx context.Context, dbname, schema, table string, keys []string, params ...interface{}) adapters.Scanner {
	_ = "STUB: not implemented"
	return *new(adapters.Scanner)
}

// BatchInsertCopyCtx indicates an expected call of BatchInsertCopyCtx.
func (mr *MockAdapterMockRecorder) BatchInsertCopyCtx(ctx, dbname, schema, table, keys interface{}, params ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// BatchInsertValues mocks base method.
func (m *MockAdapter) BatchInsertValues(SQL string, params ...interface{}) adapters.Scanner {
	_ = "STUB: not implemented"
	return *new(adapters.Scanner)
}

// BatchInsertValues indicates an expected call of BatchInsertValues.
func (mr *MockAdapterMockRecorder) BatchInsertValues(SQL interface{}, params ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// BatchInsertValuesCtx mocks base method.
func (m *MockAdapter) BatchInsertValuesCtx(ctx context.Context, SQL string, params ...interface{}) adapters.Scanner {
	_ = "STUB: not implemented"
	return *new(adapters.Scanner)
}

// BatchInsertValuesCtx indicates an expected call of BatchInsertValuesCtx.
func (mr *MockAdapterMockRecorder) BatchInsertValuesCtx(ctx, SQL interface{}, params ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CountByRequest mocks base method.
func (m *MockAdapter) CountByRequest(req *http.Request) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// CountByRequest indicates an expected call of CountByRequest.
func (mr *MockAdapterMockRecorder) CountByRequest(req interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DatabaseClause mocks base method.
func (m *MockAdapter) DatabaseClause(req *http.Request) (string, bool) {
	_ = "STUB: not implemented"
	return "", false
}

// DatabaseClause indicates an expected call of DatabaseClause.
func (mr *MockAdapterMockRecorder) DatabaseClause(req interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DatabaseOrderBy mocks base method.
func (m *MockAdapter) DatabaseOrderBy(order string, hasCount bool) string {
	_ = "STUB: not implemented"
	return ""
}

// DatabaseOrderBy indicates an expected call of DatabaseOrderBy.
func (mr *MockAdapterMockRecorder) DatabaseOrderBy(order, hasCount interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DatabaseWhere mocks base method.
func (m *MockAdapter) DatabaseWhere(requestWhere string) string {
	_ = "STUB: not implemented"
	return ""
}

// DatabaseWhere indicates an expected call of DatabaseWhere.
func (mr *MockAdapterMockRecorder) DatabaseWhere(requestWhere interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Delete mocks base method.
func (m *MockAdapter) Delete(SQL string, params ...interface{}) adapters.Scanner {
	_ = "STUB: not implemented"
	return *new(adapters.Scanner)
}

// Delete indicates an expected call of Delete.
func (mr *MockAdapterMockRecorder) Delete(SQL interface{}, params ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteCtx mocks base method.
func (m *MockAdapter) DeleteCtx(ctx context.Context, SQL string, params ...interface{}) adapters.Scanner {
	_ = "STUB: not implemented"
	return *new(adapters.Scanner)
}

// DeleteCtx indicates an expected call of DeleteCtx.
func (mr *MockAdapterMockRecorder) DeleteCtx(ctx, SQL interface{}, params ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteSQL mocks base method.
func (m *MockAdapter) DeleteSQL(database, schema, table string) string {
	_ = "STUB: not implemented"
	return ""
}

// DeleteSQL indicates an expected call of DeleteSQL.
func (mr *MockAdapterMockRecorder) DeleteSQL(database, schema, table interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteWithTransaction mocks base method.
func (m *MockAdapter) DeleteWithTransaction(tx *sql.Tx, SQL string, params ...interface{}) adapters.Scanner {
	_ = "STUB: not implemented"
	return *new(adapters.Scanner)
}

// DeleteWithTransaction indicates an expected call of DeleteWithTransaction.
func (mr *MockAdapterMockRecorder) DeleteWithTransaction(tx, SQL interface{}, params ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DistinctClause mocks base method.
func (m *MockAdapter) DistinctClause(r *http.Request) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// DistinctClause indicates an expected call of DistinctClause.
func (mr *MockAdapterMockRecorder) DistinctClause(r interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ExecuteScripts mocks base method.
func (m *MockAdapter) ExecuteScripts(method, sql string, values []interface{}) adapters.Scanner {
	_ = "STUB: not implemented"
	return *new(adapters.Scanner)
}

// ExecuteScripts indicates an expected call of ExecuteScripts.
func (mr *MockAdapterMockRecorder) ExecuteScripts(method, sql, values interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ExecuteScriptsCtx mocks base method.
func (m *MockAdapter) ExecuteScriptsCtx(ctx context.Context, method, sql string, values []interface{}) adapters.Scanner {
	_ = "STUB: not implemented"
	return *new(adapters.Scanner)
}

// ExecuteScriptsCtx indicates an expected call of ExecuteScriptsCtx.
func (mr *MockAdapterMockRecorder) ExecuteScriptsCtx(ctx, method, sql, values interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// FieldsPermissions mocks base method.
func (m *MockAdapter) FieldsPermissions(r *http.Request, table, op string, userName string) ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// FieldsPermissions indicates an expected call of FieldsPermissions.
func (mr *MockAdapterMockRecorder) FieldsPermissions(r, table, op, userName interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetDatabase mocks base method.
func (m *MockAdapter) GetDatabase() string { _ = "STUB: not implemented"; return "" }

// GetDatabase indicates an expected call of GetDatabase.
func (mr *MockAdapterMockRecorder) GetDatabase() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetScript mocks base method.
func (m *MockAdapter) GetScript(verb, folder, scriptName string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetScript indicates an expected call of GetScript.
func (mr *MockAdapterMockRecorder) GetScript(verb, folder, scriptName interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetTransaction mocks base method.
func (m *MockAdapter) GetTransaction() (*sql.Tx, error) { _ = "STUB: not implemented"; return nil, nil }

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockAdapterMockRecorder) GetTransaction() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetTransactionCtx mocks base method.
func (m *MockAdapter) GetTransactionCtx(ctx context.Context) (*sql.Tx, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetTransactionCtx indicates an expected call of GetTransactionCtx.
func (mr *MockAdapterMockRecorder) GetTransactionCtx(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GroupByClause mocks base method.
func (m *MockAdapter) GroupByClause(r *http.Request) string { _ = "STUB: not implemented"; return "" }

// GroupByClause indicates an expected call of GroupByClause.
func (mr *MockAdapterMockRecorder) GroupByClause(r interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Insert mocks base method.
func (m *MockAdapter) Insert(SQL string, params ...interface{}) adapters.Scanner {
	_ = "STUB: not implemented"
	return *new(adapters.Scanner)
}

// Insert indicates an expected call of Insert.
func (mr *MockAdapterMockRecorder) Insert(SQL interface{}, params ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// InsertCtx mocks base method.
func (m *MockAdapter) InsertCtx(ctx context.Context, SQL string, params ...interface{}) adapters.Scanner {
	_ = "STUB: not implemented"
	return *new(adapters.Scanner)
}

// InsertCtx indicates an expected call of InsertCtx.
func (mr *MockAdapterMockRecorder) InsertCtx(ctx, SQL interface{}, params ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// InsertSQL mocks base method.
func (m *MockAdapter) InsertSQL(database, schema, table, names, placeholders string) string {
	_ = "STUB: not implemented"
	return ""
}

// InsertSQL indicates an expected call of InsertSQL.
func (mr *MockAdapterMockRecorder) InsertSQL(database, schema, table, names, placeholders interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// InsertWithTransaction mocks base method.
func (m *MockAdapter) InsertWithTransaction(tx *sql.Tx, SQL string, params ...interface{}) adapters.Scanner {
	_ = "STUB: not implemented"
	return *new(adapters.Scanner)
}

// InsertWithTransaction indicates an expected call of InsertWithTransaction.
func (mr *MockAdapterMockRecorder) InsertWithTransaction(tx, SQL interface{}, params ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// JoinByRequest mocks base method.
func (m *MockAdapter) JoinByRequest(r *http.Request) ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// JoinByRequest indicates an expected call of JoinByRequest.
func (mr *MockAdapterMockRecorder) JoinByRequest(r interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// OrderByRequest mocks base method.
func (m *MockAdapter) OrderByRequest(r *http.Request) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// OrderByRequest indicates an expected call of OrderByRequest.
func (mr *MockAdapterMockRecorder) OrderByRequest(r interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PaginateIfPossible mocks base method.
func (m *MockAdapter) PaginateIfPossible(r *http.Request) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// PaginateIfPossible indicates an expected call of PaginateIfPossible.
func (mr *MockAdapterMockRecorder) PaginateIfPossible(r interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ParseBatchInsertRequest mocks base method.
func (m *MockAdapter) ParseBatchInsertRequest(r *http.Request) (string, string, []interface{}, error) {
	_ = "STUB: not implemented"
	return "", "", nil, nil
}

// ParseBatchInsertRequest indicates an expected call of ParseBatchInsertRequest.
func (mr *MockAdapterMockRecorder) ParseBatchInsertRequest(r interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ParseInsertRequest mocks base method.
func (m *MockAdapter) ParseInsertRequest(r *http.Request) (string, string, []interface{}, error) {
	_ = "STUB: not implemented"
	return "", "", nil, nil
}

// ParseInsertRequest indicates an expected call of ParseInsertRequest.
func (mr *MockAdapterMockRecorder) ParseInsertRequest(r interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ParseScript mocks base method.
func (m *MockAdapter) ParseScript(scriptPath string, templateData map[string]interface{}) (string, []interface{}, error) {
	_ = "STUB: not implemented"
	return "", nil, nil
}

// ParseScript indicates an expected call of ParseScript.
func (mr *MockAdapterMockRecorder) ParseScript(scriptPath, templateData interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Query mocks base method.
func (m *MockAdapter) Query(SQL string, params ...interface{}) adapters.Scanner {
	_ = "STUB: not implemented"
	return *new(adapters.Scanner)
}

// Query indicates an expected call of Query.
func (mr *MockAdapterMockRecorder) Query(SQL interface{}, params ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// QueryCount mocks base method.
func (m *MockAdapter) QueryCount(SQL string, params ...interface{}) adapters.Scanner {
	_ = "STUB: not implemented"
	return *new(adapters.Scanner)
}

// QueryCount indicates an expected call of QueryCount.
func (mr *MockAdapterMockRecorder) QueryCount(SQL interface{}, params ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// QueryCountCtx mocks base method.
func (m *MockAdapter) QueryCountCtx(ctx context.Context, SQL string, params ...interface{}) adapters.Scanner {
	_ = "STUB: not implemented"
	return *new(adapters.Scanner)
}

// QueryCountCtx indicates an expected call of QueryCountCtx.
func (mr *MockAdapterMockRecorder) QueryCountCtx(ctx, SQL interface{}, params ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// QueryCtx mocks base method.
func (m *MockAdapter) QueryCtx(ctx context.Context, SQL string, params ...interface{}) adapters.Scanner {
	_ = "STUB: not implemented"
	return *new(adapters.Scanner)
}

// QueryCtx indicates an expected call of QueryCtx.
func (mr *MockAdapterMockRecorder) QueryCtx(ctx, SQL interface{}, params ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReturningByRequest mocks base method.
func (m *MockAdapter) ReturningByRequest(r *http.Request) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// ReturningByRequest indicates an expected call of ReturningByRequest.
func (mr *MockAdapterMockRecorder) ReturningByRequest(r interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SchemaClause mocks base method.
func (m *MockAdapter) SchemaClause(req *http.Request) (string, bool) {
	_ = "STUB: not implemented"
	return "", false
}

// SchemaClause indicates an expected call of SchemaClause.
func (mr *MockAdapterMockRecorder) SchemaClause(req interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SchemaOrderBy mocks base method.
func (m *MockAdapter) SchemaOrderBy(order string, hasCount bool) string {
	_ = "STUB: not implemented"
	return ""
}

// SchemaOrderBy indicates an expected call of SchemaOrderBy.
func (mr *MockAdapterMockRecorder) SchemaOrderBy(order, hasCount interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SchemaTablesClause mocks base method.
func (m *MockAdapter) SchemaTablesClause() string { _ = "STUB: not implemented"; return "" }

// SchemaTablesClause indicates an expected call of SchemaTablesClause.
func (mr *MockAdapterMockRecorder) SchemaTablesClause() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SchemaTablesOrderBy mocks base method.
func (m *MockAdapter) SchemaTablesOrderBy(order string) string {
	_ = "STUB: not implemented"
	return ""
}

// SchemaTablesOrderBy indicates an expected call of SchemaTablesOrderBy.
func (mr *MockAdapterMockRecorder) SchemaTablesOrderBy(order interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SchemaTablesWhere mocks base method.
func (m *MockAdapter) SchemaTablesWhere(requestWhere string) string {
	_ = "STUB: not implemented"
	return ""
}

// SchemaTablesWhere indicates an expected call of SchemaTablesWhere.
func (mr *MockAdapterMockRecorder) SchemaTablesWhere(requestWhere interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SelectFields mocks base method.
func (m *MockAdapter) SelectFields(fields []string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// SelectFields indicates an expected call of SelectFields.
func (mr *MockAdapterMockRecorder) SelectFields(fields interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SelectSQL mocks base method.
func (m *MockAdapter) SelectSQL(selectStr, database, schema, table string) string {
	_ = "STUB: not implemented"
	return ""
}

// SelectSQL indicates an expected call of SelectSQL.
func (mr *MockAdapterMockRecorder) SelectSQL(selectStr, database, schema, table interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetByRequest mocks base method.
func (m *MockAdapter) SetByRequest(r *http.Request, initialPlaceholderID int) (string, []interface{}, error) {
	_ = "STUB: not implemented"
	return "", nil, nil
}

// SetByRequest indicates an expected call of SetByRequest.
func (mr *MockAdapterMockRecorder) SetByRequest(r, initialPlaceholderID interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetDatabase mocks base method.
func (m *MockAdapter) SetDatabase(name string) { _ = "STUB: not implemented"; return }

// SetDatabase indicates an expected call of SetDatabase.
func (mr *MockAdapterMockRecorder) SetDatabase(name interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ShowTable mocks base method.
func (m *MockAdapter) ShowTable(schema, table string) adapters.Scanner {
	_ = "STUB: not implemented"
	return *new(adapters.Scanner)
}

// ShowTable indicates an expected call of ShowTable.
func (mr *MockAdapterMockRecorder) ShowTable(schema, table interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ShowTableCtx mocks base method.
func (m *MockAdapter) ShowTableCtx(ctx context.Context, schema, table string) adapters.Scanner {
	_ = "STUB: not implemented"
	return *new(adapters.Scanner)
}

// ShowTableCtx indicates an expected call of ShowTableCtx.
func (mr *MockAdapterMockRecorder) ShowTableCtx(ctx, schema, table interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// TableClause mocks base method.
func (m *MockAdapter) TableClause() string { _ = "STUB: not implemented"; return "" }

// TableClause indicates an expected call of TableClause.
func (mr *MockAdapterMockRecorder) TableClause() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// TableOrderBy mocks base method.
func (m *MockAdapter) TableOrderBy(order string) string { _ = "STUB: not implemented"; return "" }

// TableOrderBy indicates an expected call of TableOrderBy.
func (mr *MockAdapterMockRecorder) TableOrderBy(order interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// TablePermissions mocks base method.
func (m *MockAdapter) TablePermissions(table, op, userName string) bool {
	_ = "STUB: not implemented"
	return false
}

// TablePermissions indicates an expected call of TablePermissions.
func (mr *MockAdapterMockRecorder) TablePermissions(table, op, userName interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// TableWhere mocks base method.
func (m *MockAdapter) TableWhere(requestWhere string) string { _ = "STUB: not implemented"; return "" }

// TableWhere indicates an expected call of TableWhere.
func (mr *MockAdapterMockRecorder) TableWhere(requestWhere interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Update mocks base method.
func (m *MockAdapter) Update(SQL string, params ...interface{}) adapters.Scanner {
	_ = "STUB: not implemented"
	return *new(adapters.Scanner)
}

// Update indicates an expected call of Update.
func (mr *MockAdapterMockRecorder) Update(SQL interface{}, params ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateCtx mocks base method.
func (m *MockAdapter) UpdateCtx(ctx context.Context, SQL string, params ...interface{}) adapters.Scanner {
	_ = "STUB: not implemented"
	return *new(adapters.Scanner)
}

// UpdateCtx indicates an expected call of UpdateCtx.
func (mr *MockAdapterMockRecorder) UpdateCtx(ctx, SQL interface{}, params ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateSQL mocks base method.
func (m *MockAdapter) UpdateSQL(database, schema, table, setSyntax string) string {
	_ = "STUB: not implemented"
	return ""
}

// UpdateSQL indicates an expected call of UpdateSQL.
func (mr *MockAdapterMockRecorder) UpdateSQL(database, schema, table, setSyntax interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateWithTransaction mocks base method.
func (m *MockAdapter) UpdateWithTransaction(tx *sql.Tx, SQL string, params ...interface{}) adapters.Scanner {
	_ = "STUB: not implemented"
	return *new(adapters.Scanner)
}

// UpdateWithTransaction indicates an expected call of UpdateWithTransaction.
func (mr *MockAdapterMockRecorder) UpdateWithTransaction(tx, SQL interface{}, params ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WhereByRequest mocks base method.
func (m *MockAdapter) WhereByRequest(r *http.Request, initialPlaceholderID int) (string, []interface{}, error) {
	_ = "STUB: not implemented"
	return "", nil, nil
}

// WhereByRequest indicates an expected call of WhereByRequest.
func (mr *MockAdapterMockRecorder) WhereByRequest(r, initialPlaceholderID interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
