// Code generated by MockGen. DO NOT EDIT.
// Source: adapters/scanner.go

// Package mockgen is a generated GoMock package.
package mockgen

import (
	gomock "github.com/golang/mock/gomock"
)

// MockScanner is a mock of Scanner interface.
type MockScanner struct {
	ctrl     *gomock.Controller
	recorder *MockScannerMockRecorder
}

// MockScannerMockRecorder is the mock recorder for MockScanner.
type MockScannerMockRecorder struct {
	mock *MockScanner
}

// NewMockScanner creates a new mock instance.
func NewMockScanner(ctrl *gomock.Controller) *MockScanner { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScanner) EXPECT() *MockScannerMockRecorder {
	_ = "STUB: not implemented"

	// Bytes mocks base method.
	return nil
}

func (m *MockScanner) Bytes() []byte { _ = "STUB: not implemented"; return nil }

// Bytes indicates an expected call of Bytes.
func (mr *MockScannerMockRecorder) Bytes() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Err mocks base method.
func (m *MockScanner) Err() error { _ = "STUB: not implemented"; return nil }

// Err indicates an expected call of Err.
func (mr *MockScannerMockRecorder) Err() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Scan mocks base method.
func (m *MockScanner) Scan(arg0 interface{}) (int, error) { _ = "STUB: not implemented"; return 0, nil }

// Scan indicates an expected call of Scan.
func (mr *MockScannerMockRecorder) Scan(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
